spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/spmia-realm # Use localhost if your Spring app runs outside Docker
          # Use keycloak if your Spring app runs inside Docker Compose with a service named keycloak: http://keycloak:8080/realms/spmia-realm
  cloud:
    function:
      definition: organizationChangeConsumer
    stream:
      bindings:
        organizationChangeConsumer-in-0:
          destination: orgChangeTopic
          group: licensing-service
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  cache:
    type: redis
    redis:
      time-to-live: 10m

  data:
    redis:
      host: localhost
      port: 6379

resilience4j.circuitbreaker:
    instances:
      licenseService:
        registerHealthIndicator: true     # Exposes this circuit breaker via Spring Boot Actuator: Useful for monitoring (OPEN / CLOSED / HALF_OPEN)
        # ringBufferSizeInClosedState: 5    # Legacy setting (from older Resilience4j versions). In modern versions, this is replaced by: slidingWindowSize
                                          # If both exist:
                                          # - slidingWindowSize wins
                                          # - ringBufferSizeInClosedState can be ignored
                                          # 👉 You can safely remove this in new projects.
        ringBufferSizeInHalfOpenState: 3  # Number of trial calls allowed in HALF_OPEN state.
                                          # When the circuit moves from OPEN → HALF_OPEN:
                                          # - Only 3 calls are allowed
                                          # - If they succeed → circuit closes
                                          # - If they fail → circuit reopens
        waitDurationInOpenState: 10s      # How long the circuit stays OPEN before trying again. After 10s → moves to HALF_OPEN
        failureRateThreshold: 50          # Percentage of failed calls that triggers OPEN state. Example (with window size = 3):
                                          # 2 failures out of 3 → 66% → OPEN
                                          # 1 failure out of 3 → 33% → stays CLOSED
        recordExceptions:                 # These exceptions are treated as failures. If one of these is thrown → failure count increases. Any exception not listed here is treated as a success unless you configure ignoreExceptions
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
        slidingWindowType: COUNT_BASED    # How failures are calculated.
                                          # - COUNT_BASED → based on last N calls
                                          # - TIME_BASED → based on last N seconds
        slidingWindowSize: 3              # Number of calls in the evaluation window; With COUNT_BASED, this means: "Only the last 3 calls are considered."
        minimumNumberOfCalls: 3           # CircuitBreaker won’t evaluate failures until at least 3 calls happen.
                                          # Prevents the circuit from opening too early due to noise.

      organizationService:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 6
        ringBufferSizeInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60

resilience4j.bulkhead:
  instances:
    bulkheadLicenseService:
      maxWaitDuration: 10ms          # maximum amount of time to block a thread
      maxConcurrentCalls: 20         # The maximum number of concurrent requests

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 1           # The maximum number of threads in the thread pool
      coreThreadPoolSize: 1          # The core thread pool size
      queueCapacity: 1               # The queue’s capacity (Waiting requests)
      keepAliveDuration: 20ms        # Idle thread timeout (The maximum time that idle threads wait for new tasks before terminating)

resilience4j.retry:
  instances:
    retryLicenseService:
      maxAttempts: 3
      waitDuration: 10s             # or 10000ms
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  instances:
    licenseService:
      timeoutDuration: 0            # 1000ms
      limitRefreshPeriod: 10s
      limitForPeriod: 2

info:
  app:
    version: 1.0.0

logging:
  logstash:
    destination: ${LOGSTASH_DESTINATION:localhost:5000}

  level:
    root: INFO
    org.springframework: INFO
    com.optimagrowth: DEBUG